FROM node:20 AS build
WORKDIR /app
COPY FrontEndTicketProject/package*.json ./
RUN npm install
COPY FrontEndTicketProject/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY ticket-infra/nginx.conf /etc/nginx/conf.d/default.conf
