# ticket-infra/docker-compose.yml
version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tickets-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: tickets-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
